// <auto-generated />
namespace Maslshop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FilteredUsersRev1SP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FilteredUsersRev1SP));
        
        string IMigrationMetadata.Id
        {
            get { return "201806221008450_FilteredUsersRev1SP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
